# Generated by Django 5.0.1 on 2024-02-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='size',
            name='slug',
        ),
    ]
